#!/bin/bash
set -u -e -C;
shopt -s nullglob;

cd "$(dirname "$0")";

../feedback \
    overview=punktestand feedback=group/%/punkte \
    reqdTotal=50 reqdEach=10 maxLow=3 \
    maxPoints=max_punkte \
    groups=groups \
    $(test "${1:-}" && echo "lim=${1}" || true) \
    tutor-{a,b}.points

less -S -x30,40 punktestand
