#!/bin/bash
set -u -e -C;
shopt -s nullglob;

cd "$(dirname "$0")";

if ! test -d group; then
    mkdir -p group/{001..34};
fi;

../feedback \
    overview=punktestand feedback=group/%/punkte \
    reqdTotal=50 reqdEach=10 maxLow=3 \
    maxPoints=max_punkte \
    groups=groups \
    $(test "${1:-}" && echo "lim=${1}" || true) \
    alice.allison bob.bobbington

less -S -x30,40 punktestand
